using System;

namespace StorageService.Exceptions
{
	internal sealed class BattleAlreadyFinishedException : Exception
	{
		
	}
}